version: "3"

services:
  server:
    build:
      context: ./server/
    ports:
      - 8000:8000
  client:
    build:
      context: ./client/
    depends_on: 
      - server
    links: 
      - server
    